version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - database

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   environment:
  #     - SERVER_HOST=server
  #     - SERVER_PORT=8443
  #   depends_on:
  #     - server

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: transactions
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  payment_network:
    driver: bridge

volumes:
  db_data: